### ISSUE TITLE
error when ejabberd restarts

### ISSUE THREAD

**Issue by vliedel** [node-xmpp/node-xmpp#150]
When I restart ejabberd while logged in via node-xmpp, node-xmpp crashes:

```
events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at Connection.EventEmitter.emit (events.js:74:15)
    at Connection.onStanza (/home/vliedel/test/node_modules/node-xmpp/lib/xmpp/connection.js:248:14)
    at StreamParser.<anonymous> (/home/vliedel/test/node_modules/node-xmpp/lib/xmpp/connection.js:154:14)
    at StreamParser.EventEmitter.emit (events.js:95:17)
    at SaxLtx.<anonymous> (/home/vliedel/test/node_modules/node-xmpp/lib/xmpp/stream_parser.js:53:22)
    at SaxLtx.EventEmitter.emit (events.js:95:17)
    at SaxLtx.write (/home/vliedel/test/node_modules/node-xmpp/node_modules/ltx/lib/sax_ltx.js:83:9)
    at StreamParser.write (/home/vliedel/test/node_modules/node-xmpp/lib/xmpp/stream_parser.js:97:21)
    at Connection.onData (/home/vliedel/test/node_modules/node-xmpp/lib/xmpp/connection.js:206:21)
```

I "fixed" this by adding:
```
this.connection.addListener('error', function() {
    self.emit('error');
});
```
in session.js, so that i can handle the error. But this shouldn't introduce an error in the first place.

Using:
- Ubuntu 13.04
- node-js 0.10.9
- node-xmpp 0.6.0

**Comment by sonnyp** [comment]
closing this, fixed since
