### ISSUE TITLE
Keep getting ECONNRESET every 3 o 2 minutes when connected to Hipchat's XMPP

### ISSUE THREAD

**Issue by cesarvarela** [node-xmpp/node-xmpp#394]
```
{ Error: read ECONNRESET
at exports._errnoException (util.js:1034:11)
at TLSWrap.onread (net.js:580:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
```

**Comment by cesarvarela** [comment]
```
     this.client.on('online', () => {

            this.client.send(new XmppClient.Stanza('presence', {})
                .c('show').t('chat').up()
                .c('status').t('Puppe')
            )

            this.client.connection.socket.setTimeout(0);
            this.client.connection.socket.setKeepAlive(true, 10000);
        });
```

I'm setting the keep alives on the `online` handler, I've read somewhere that I should reply to ping stanzas, maybe that's what's causing the problem? Can someone give an example on how to to that?

thanks in advance.

**Comment by cesarvarela** [comment]
From hipchat's docs:

```
Connections are dropped after 150s of inactivity. We suggest sending a single space (" ") as keep-alive data every 60 seconds.
```
How can I do this with this client?

**Comment by cesarvarela** [comment]
Well, got it working, this is what needs to be done for hipchat's xmpp
```js
            setInterval(() => {
                this.client.send(new XmppClient.Stanza('r'));
            }, 60000)
```
